---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При переключении на русскую версию сайта описание товаров должно менятся на русский язык
  - При переключении на русскую версию сайта стоимость товаров должна меняться на российские рубли
  - При переключении на русскую версию сайта названия категорий товаров должны быть на русском языке
  - Список производителей должен меняться при выборе соответствующей категории товаров
  - Окно выбора языка должно закрываться автоматически при нажатии кнопки мыши в любом другом месте сайта
  - При добавлении товара в корзину должно выводиться окно с выбором количества добавляемого товара и соответсвующим подтверждением
  - При удалении товара из корзины должно всплывать окно с пожтверждением действия
  - Пользователь должен иметь возможность редактировать количество товара в корзине
  - При оформлении заказа должно всплывать окно с подтверждением действия
  - Пользователь должен иметь возможность увеличить или открыть в полном окне картинку товара в описании товара
  - Пользователь должен иметь возможность переключать картинки товара в описании товара
  - Пользователь должен иметь возможность открыть полное текстовое описание товара во вкладке описания товара
  - Количество оставшегося товара в магазине должно быть соответсвующе подписано
  - При нажатии надписи Hexlet Store должна открываться вкладка магазина
  - Пользователь должен иметь возможность сбросить поиск товара по категории
